version: '3.9'

services:
  nestjs:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: ./srcs/nestjs-backend
      target: development
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - transcendence-net
    volumes:
      - ./srcs/nestjs-backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  transcendence-net:
