version: '3.9'

services:
  nestjs:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: ./srcs/nestjs-backend
      target: development
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - transcendence-net
    volumes:
      - ./srcs/react-frontend/src/game/shared:/usr/src/app/src/game/shared
      - ./srcs/nestjs-backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  
  react:
    container_name: react_frontend_dev
    image: react_frontend_dev:1.0.0
    build:
      context: ./srcs/react-frontend
      target: development
    command: npm run start
    ports:
      - 80:3000
    networks:
      - transcendence-net
    volumes:
      - ./srcs/react-frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped


networks:
  transcendence-net:
