version: '3.9'

services:
  nestjs:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: ./srcs/nestjs-backend/
      target: production
    command: npm run start:prod
    ports:
      - 3030:3000
      - 9229:9229
    networks:
      - transcendence-net
    volumes:
      - /usr/src/app/node_modules
    restart: unless-stopped
  react:
    container_name: react_frontend_prod
    image: react_frontend_prod:1.0.0
    build:
      context: ./srcs/react-frontend
      target: production
    # command: npm run build && echo pusyyyy # && serve -s build
    ports:
      - 80:3000
    networks:
      - transcendence-net
    volumes:
      - /usr/src/app/node_modules
    restart: unless-stopped



networks:
  transcendence-net:
